---
title: "Influencer Audience Growth Analysis"
author: "Esteban Castillo"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 10,
  fig.height = 6
)
```

## Introduction

This document analyzes audience changes for content creators, focusing on the relationship between audience, its own past values, recent engagement, and posts per day. 



```{r load-libraries}
# Load required libraries

```

## Post Frequency

```{r load-data}
# Load and prepare the influencer data
models_audience_change %>%
  select( summary,source) %>%
  unnest(summary) %>%
  ggplot(aes(x = source, y = r.squared)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "R-squared of Audience Change vs. Posts per Day",
    x = "Audience Tier",
    y = "R-squared"
  ) + 
  theme_minimal()
models_audience_change %>%
  select( coefficients,source) %>%
  unnest(coefficients) %>% 
  ggplot(aes(x = source, y = estimate)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Coefficients Audience Change vs. Posts per Day",
    x = "Audience Tier",
    y = "Coefficients"
  ) +
  theme_minimal()+facet_wrap(term~.)
```

## Engagement Rate Analysis


```{r correlation}
models_audience_change_er %>%
  select( summary,source) %>%
  unnest(summary) %>%
  ggplot(aes(x = source, y = r.squared)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "R-squared of Audience Change vs. Engagement Rate last 10 posts",
    x = "Audience Tier",
    y = "R-squared"
  ) +
  theme_minimal()
models_audience_change_er %>%
  select( coefficients,source) %>%
  unnest(coefficients) %>% 
  ggplot(aes(x = source, y = estimate)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Coefficients Audience Change vs. Engagement Rate last 10 posts",
    x = "Audience Tier",
    y = "Coefficients"
  ) +
  theme_minimal()+facet_wrap(term~.)

```

### How does predictability vary from each starting audience? 

```{r linear-model}
df_sum_f %>% 
  ggplot(aes(x=starting_audience,y=test_MeanAbsoluteError))+geom_point()+scale_x_log10()+
  geom_smooth(method='lm')+
  scale_x_log10()+facet_wrap(source~.,scales = 'free')
```

### Is audience growth as predictable in each platform?

```{r actual-vs-predicted}
df_forecast_sum %>% 
  ggplot(aes(x=source,y=test_MeanAbsolutePercentageError_mean))+geom_col()
```

